### PR TITLE
Ghidra 10.0 support

### LINKED ISSUE #70: Ghidra 10.0 support
Ghidra 10 will release very soon, and it has some radical changes to the Pcode injection stuff, so bitrot in ghidra-emotionengine sets in:

- Ghidra 9.1.2: https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_9.1.2_build/Ghidra/Processors/JVM/src/main/java/ghidra/app/util/pcodeInject/InjectPayloadJava.java (this is roughly what ghidra-emotionengine uses in InjectPayloadVu.java)
- Ghidra 9.2.4: https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_9.2.4_build/Ghidra/Processors/JVM/src/main/java/ghidra/app/util/pcodeInject/InjectPayloadJava.java (still compatible with ghidra-emotionengine)
- Ghidra 10.0: https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.0/Ghidra/Processors/JVM/src/main/java/ghidra/app/util/pcodeInject/InjectPayloadJava.java (no longer compatible with ghidra-emotionengine, API use broke)

Some changes which have to do with this (5 minute job of git blame; but I have no idea what I'm doing, because the Ghidra codebase is so convoluted):
- https://github.com/NationalSecurityAgency/ghidra/commit/a5d4ca3cab650b95fa1b9c7bfc21e95d77d92e1c
- https://github.com/NationalSecurityAgency/ghidra/commit/9c2ce9b3953916ce8e3432e61fd39ccf183e7018
- https://github.com/NationalSecurityAgency/ghidra/commit/ed82c2cb34ec3fbcee725db4f8f15f4adcaf4743

**Motivation**

Ghidra 10 has a couple of killer features:

- Better re-export of ELF files
- Support for `for-loop` in decompiler
- Support for new gradle versions
- Better SLEIGH emulation interface
- Tracing and debugging

### PR DESCRIPTION
**Pull request by astrelsky**
I'm not sure what the values should be for the CI. I am also uncertain what branch this should go in as it breaks support for all versions < Ghidra 10.0.

Resolves #70

### CODE REVIEW

**Comment by beardypig** [comment]
There is an issue with the CI builder for Ghidra 10 that needs to be resolved. 
It might be worth setting up a more complicated branch structure to handled the major versions of Ghidra, I will make some time to look at it later today or over the weekend.

**Comment by SpaceDog61** [comment]
Any news about the support of the  Ghidra 10?

**Comment by astrelsky** [comment]
> Any news about the support of the Ghidra 10?

You may use this in the meantime if you'd like. I did some manual renaming after building so if it is broken lmk.

[ghidra_10.0_PUBLIC_20210710_ghidra-emotionengine.zip](https://github.com/beardypig/ghidra-emotionengine/files/6796121/ghidra_10.0_PUBLIC_20210710_ghidra-emotionengine.zip)

**Comment by JayFoxRox** [comment]
> You may use this in the meantime if you'd like. I did some manual renaming after building so if it is broken lmk.

The linked file does not seem to work for me in Ghidra 10.0.2 (Arch Linux package ghidra-10.0.2-1).

> There is an issue with the CI builder for Ghidra 10 that needs to be resolved.

Was this related to the changes in how Ghidra is published, or something else? Since your comment, there have been changes to the CI script that we use: https://github.com/er28-0652/setup-ghidra/commit/78856978c498ab739b64cf4ed8b25c6e7b7740b7

Ghidra 10.x has been out for a while now, too. So it's very unfortunate that the latest release of this plugin is not up-to-date.

*Edit: I still wasn't able to build ghidra-emotionengine locally (any branch), so I used GitHub actions to build it for 10.0.2 now: https://github.com/JayFoxRox/ghidra-emotionengine/releases/tag/vUnknown-10.x*

**Comment by VelocityRa** [comment]
@beardypig Can you _please_ merge this?
Ghidra 10 has been out for 3 months at this point.

**Comment by Risae** [comment]
@astrelsky Will this also support the new Ghidra releases? (10.0+)

**Comment by astrelsky** [comment]
> @astrelsky Will this also support the new Ghidra releases? (10.0+)

Of course.

<https://github.com/astrelsky/ghidra-emotionengine/releases/tag/latest>

**Comment by Risae** [comment]
@astrelsky Thank you very much!

**Pull request merged**
